### ISSUE TITLE
ImportError: cannot import name 'MutableMapping' from 'collections'

### ISSUE THREAD

**Issue by NAKNAO-nnct** [yanoshi/yootto#20]
```
❯ python --version
Python 3.11.6

❯ yootto auth
Traceback (most recent call last):
  File "/opt/homebrew/bin/yootto", line 5, in <module>
    from yootto.core import main
  File "/opt/homebrew/lib/python3.11/site-packages/yootto/core.py", line 20, in <module>
    from tinytag import TinyTag
  File "/opt/homebrew/lib/python3.11/site-packages/tinytag/__init__.py", line 3, in <module>
    from .tinytag import TinyTag, TinyTagException, ID3, Ogg, Wave, Flac
  File "/opt/homebrew/lib/python3.11/site-packages/tinytag/tinytag.py", line 36, in <module>
    from collections import MutableMapping, OrderedDict
ImportError: cannot import name 'MutableMapping' from 'collections' (/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/__init__.py)
```

**Comment by NAKNAO-nnct** [comment]
https://github.com/devsnd/tinytag/pull/110
 
tinytag の version を上げる必要がある
